name: steam-deploy

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: steam-workshop-upload
        uses: m00nl1ght-dev/steam-workshop-deploy@v1
        with: 
          appId: 294100 # Game's Steam App ID
          publishedFileId: 3232242247 # Your mod's Steam Workshop ID
          path: '' # Path to your mod's folder from repository root
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF }}
